version: "3"

services:
  app:
    build: backend
    restart: unless-stopped
    command: "--spring.profiles.active=dev"
    ports:
      - 8080:${APP_PORT}
    environment:
      DB_HOST: db:5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      APP_PORT: ${APP_PORT}

  db:
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data/:rw

volumes:
  pg_data: