spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/covid-api
    username: postgres
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
      enabled: false
